"""Application configuration.

All settings are environment-driven (prefix ``SKINDX_``) with safe local-dev
defaults so the app boots with zero configuration. See ``.env.example``.
"""

from __future__ import annotations

from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env", env_prefix="SKINDX_", extra="ignore", case_sensitive=False
    )

    # --- general ---
    app_name: str = "skin-diagnosis-app"
    environment: str = "development"
    debug: bool = True

    # --- server ---
    host: str = "127.0.0.1"
    port: int = 8000

    # --- persistence ---
    database_url: str  # required — set SKINDX_DATABASE_URL in .env, no default

    # --- auth ---
    jwt_secret: str = "dev-insecure-change-me-0000000000000000"
    jwt_algorithm: str = "HS256"
    access_token_ttl_minutes: int = 60 * 24

    # --- object storage for uploaded images ---
    storage_backend: str = "local"  # local | s3
    storage_local_dir: str = "./var/uploads"
    storage_s3_bucket: str | None = None
    storage_s3_region: str | None = None
    signed_url_ttl_seconds: int = 900

    # --- upload constraints ---
    max_upload_bytes: int = 8 * 1024 * 1024
    allowed_image_types: tuple[str, ...] = ("image/jpeg", "image/png", "image/webp")
    min_image_dimension_px: int = 200

    # --- inference / triage ---
    inference_adapter: str = "mock"  # mock | google_vision | custom
    model_version: str = "mock-v0.1.0"
    top_k_predictions: int = 5
    # top confidence below this floor => route to "see a professional"
    referral_confidence_floor: float = 0.45

    # --- background jobs (async inference) ---
    redis_url: str 
    # True: tasks run in-process immediately (no Redis/worker needed) — local
    # dev & test default. False: tasks are queued for a real `celery worker`.
    celery_task_always_eager: bool = False

    # --- compliance ---
    policy_version: str = "1.0"
    disclaimer_text: str = (
        "This assessment is generated by software for educational and informational "
        "purposes only. It is not a medical diagnosis and cannot replace evaluation "
        "by a licensed clinician. Seek professional care for any skin concern that is "
        "painful, spreading, bleeding, changing, or persistent."
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()
